export const timelots = [
  { title: '12 AM', value: 0 },
  { title: '1 AM', value: 1 },
  { title: '2 AM', value: 2 },
  { title: '3 AM', value: 3 },
  { title: '4 AM', value: 4 },
  { title: '5 AM', value: 5 },
  { title: '6 AM', value: 6 },
  { title: '7 AM', value: 7 },
  { title: '8 AM', value: 8 },
  { title: '9 AM', value: 9 },
  { title: '10 AM', value: 10 },
  { title: '11 AM', value: 11 },
  { title: '12 PM', value: 12 },
  { title: '1 PM', value: 13 },
  { title: '2 PM', value: 14 },
  { title: '3 PM', value: 15 },
  { title: '4 PM', value: 16 },
  { title: '5 PM', value: 17 },
  { title: '6 PM', value: 18 },
  { title: '7 PM', value: 19 },
  { title: '8 PM', value: 20 },
  { title: '9 PM', value: 21 },
  { title: '10 PM', value: 22 },
  { title: '11 PM', value: 23 },
];
